### PR TITLE
Use of native OS file open dialog

### PR DESCRIPTION
**Pull request by Turro75**
This allows the use of OS shortcuts set in file manager

### CODE REVIEW

**Comment by kbwbe** [comment]
Hi Turro,
welcome back. Perhaps it is necessary to create a new option within the preferences page. The native file manager had been build in A2plus some time back, but caused problems on Ubuntu 18.04 and it's derivatives. Main problem was case sensitivity (.fcstd/.FCStd file extensions) and the filemanager did not find all files. Maybe the native file managers are working better with other OS's. So i think, a new entry on pref-page would be the best alternative.

**Comment by Turro75** [comment]
Hi Klaus,

actually I never went away, just silent :-)
Well I agree, it would be fine having this as an option. In windows it works very well as it allows the use of the shortcuts iset in the os fileopen dialog (I have many of them), in Linux it is highly file manager dependant so I bet You found it not coherent across many installations.

**Comment by kbwbe** [comment]
Hi Turro,
i am very busy at moment. I modify the prefpage probably at weekend and add the option for native filedialog.

**Comment by kbwbe** [comment]
Hi Turro,
the prefpage is modified and you can make use of the native file manager.

**Pull request merged**
