### PR TITLE
Allow multiples objects to be imported at once

### PR DESCRIPTION
**Pull request by leoheck**
Hey @kbwbe 

This PR changes the behavior of the button that imports a single object from a file. 
With this is possible to import multiple objects at once by selecting them with checkboxes. 

Here is a preview of the new import window.
image

Please, feel free to ask questions or to change anything if you like to.

### CODE REVIEW

**Comment by kbwbe** [comment]
Hi @leoheck, thanks for all your work. For testing, i have merged your PR to the new branch "multiimport". The first import of multiple parts seems to work, but updating these parts fail with a lot of problems. The internal A2p filecache is mixed up then and parts get lost. So the changes have to be debugged. I do not know whether my time today will be sufficient to do this, otherwise it will take some days.

**Comment by kbwbe** [comment]
I have reworked the PR and created a branch called "tmp". Please test this branch. If everything is ok for you i will merge it.

**Comment by leoheck** [comment]
Nice. I was about to start debugging this and I've seen your last message just now. Let me test this tmp branch here.

**Comment by leoheck** [comment]
This new `tmp` branch does not behave exactly like the other one.

For instance, I am creating a new FreeCAD project file and saving it.
Then I am importing multiples parts from another file.
- If I import Sketchs, it imports them and it closes the file. This is ok.
- If I import one or more bodies it is not closing the file from where I am importing features.

Then, after manually closing the file from where I am importing features 
- If I am importing 1 Body only, I will be able to place it freely in the canvas with the mouse.
- If I am importing more than 1 Body then I won't be able to place objects freely during this process.

Upgrading selected parts is working just fine.
The only small issue I see is that it is not closing the file from where we are importing parts after the import.

I would suggest adding a shortcut to this menu item too. 
Since `Shift+A` is for import the whole assembly, `Ctrl+Shift+A` could be used here.

**Comment by leoheck** [comment]
- I have addressed the issue regarding the file close here https://github.com/kbwbe/A2plus/pull/429
- I added the Ctrl+Shift+A shortcut to make life easier too :)
- I also added one print line to log the line from where the parts are being imported in case we have multiples imports with the same message as in.

**Comment by leoheck** [comment]
Ah, one thing it is missing is when we cancel the import on the dialog to import multiples parts the file opened is not closed. Do you know how to do that?

**Pull request merged**
