### PR TITLE
README: Add LGTM Badges + reformatting + youtube clip fix + grammar fixes

### PR DESCRIPTION
**Pull request by luzpaz**
Once approved, I will squash commits

### CODE REVIEW

**Comment by luzpaz** [comment]
Preview: https://github.com/luzpaz/A2plus/blob/README/README.md

**Comment by kbwbe** [comment]
Hi luzpaz,
thank you for your detailed work. Especially i like the LGTM badges. I did not know about them before. The code allerts are very useful and can help to improve a lot the code quality by simple means. Perhaps i will have some questions about usage shortly.

**Comment by kbwbe** [comment]
The new README looks good to me ! LGTM
I have some questions.
My devel branch is very different to the master branch and cannot be merged at moment. This would cause a lot of trouble to all recent users.

So at first step i had to merge your PR to the devel branch. I could not rebase your PR safely to the master branch.

But as i want to have the lgtm badges within the master branch also, i updated the README file there too. Now i have two different branches with the same lgtm batches. Does this cause problems for the lgtm analysis ? Is there something what i have to change ?

**Comment by luzpaz** [comment]
I don't know the answer to that very well. maybe that is something that be configured via the `.yaml` file?  Anyway, worst thing is that it reports false positives. We'll figure it out. :wink:

**Pull request merged**
