### PR TITLE
Visibility drives Suppressed property

### PR DESCRIPTION
**Pull request by Turro75**

### CODE REVIEW

**Comment by kbwbe** [comment]
Hi Turro,
i will look this at weekend. What's the usecase for this pull request ?

**Comment by Turro75** [comment]
Hi Klaus,

This allows the user to suppress the constraint by making it not visible.
In my opinion it is more easy identifying suppressed constraints

I see that github generated a commit that propose a change of the whole
a2p_solversystem.py, actually I modified only the beginning of loadsystem
(bold lines):

if hasattr(obj,'Suppressed'):
#modify suppressed properties according to visibility of constraint
*obj.Suppressed = not obj.ViewObject.isVisible()*
#update even the mirrored constraint
*doc.getObject(obj.Name+'_mirror').Suppressed = obj.Suppressed*
* doc.getObject(obj.Name+'_mirror').ViewObject.Visibility =
obj.ViewObject.isVisible()*
#if the mate is suppressed do not add it
if obj.Suppressed == False:
self.constraints.append(obj)

Best Regards

Valerio

Il mer 4 mar 2020, 18:28 kbwbe <notifications@github.com> ha scritto:

**Comment by kbwbe** [comment]
Aah.., i understand now. I was wondering because of the big PR, changing nearly the complete solversystem.py file. I think it is a good idea, to suppress the constraints via visibility. I will check this tomorrow.

**Comment by kbwbe** [comment]
Hi Valerio,
i have merged your PR to the master branch.
Additionally i refined the code a little bit. The visibility of the constraint and it's mirror are now synchronized by their viewproviders. Therefore now you can also use the mirrored constraint to set both constraint parts to Suppressed state.

**Pull request merged**
