### PR TITLE
Adding Icon to A2p objects

### PR DESCRIPTION
**Pull request by easyw**
I have added an icon for an A2p object to give the assembly a better look
a2p-icon

### CODE REVIEW

**Comment by easyw** [comment]
Added two Icons for Assy Part and Assy with SubAssy part
assy-subassy

**Comment by kbwbe** [comment]
Thank you very much. Looks good !

**Comment by easyw** [comment]
@kbwbe is it intentionally to merge this to 'temp' branch? do you prefer to wait to merge it to the main branch?

**Comment by kbwbe** [comment]
Gesendet: Freitag, 21. Dezember 2018 um 09:45 Uhr
Von: easyw <notifications@github.com>
An: kbwbe/A2plus <A2plus@noreply.github.com>
Cc: kbwbe <kbwbe@gmx.de>, Mention <mention@noreply.github.com>
Betreff: Re: [kbwbe/A2plus] Adding Icon to A2p objects (#131)


@kbwbe is it intentionally to merge this to 'temp' branch? do you prefer to wait to merge it to the main branch?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

Hi maurice,

a lot of people are already working with A2plus. It is one of my principles, to let nothing into master branch without at least minimal testing. Therefore i created for short time the temp branch, had a look at it and then merged it to master branch.

Last time, i had many commits in devel branch and it was out of sync with master. Usually my devel branch is not very much ahead of master and i prefer pull request to the devel branch. So everything is tested within it and goes to master some time later.

Thank you very much for your pull requests. Your are always wellcome.

Best regards,

Klaus

**Pull request merged**
