### PR TITLE
New mouse ver2 for testing

### PR DESCRIPTION
**Pull request by DanMiel**
I modified the mouse feature so that you can select two features, without using the control key and the dialog box will open with the most commonly used constraint for those features. Using the control key will activate the icons normally, or deleting the constraint will leave the icons active for selection. I think this is a much needed item. 
I added the ability to select features that are below the selected surface. Very handy once you get accustomed to it, because you do not need to turn the part over to select a non-visible feature.

### CODE REVIEW

**Comment by DanMiel** [comment]
I realized that you may not know how the feature I propose would save time so I made a couple videos to show how the new features would work in A2plus.
New mouse: The time saver is you only click 3 times to select and save a constraint. Video is 2 minutes: [https://youtu.be/BAwx8F5Yh7U](url)
Hidden layers: The time saver is you don’t need to move and rotate the assembly to mate features. Video is 4 minutes: [https://youtu.be/XFywPq9LcGU](url)

**Comment by kbwbe** [comment]
Hi Dan,
i have tested your proposal but i found bugs. 

OneButton is not working with PointOnPlane, PointOnLine, AxisPlaneParallel,AxisplaneNormal and some more.
If selecting such Elements, no Constraint-Icons get active and no standard constraint is performed.
I think, the new functionality is more a restriction than a time saver.

HiddenLayer: Not always all hiden faces are presented in the dialog.

Also i registered some crashs when trying so define a PointOnPlane constraint. But i cannot reproduce it at moment.

So this PR will not be merged. Thank you anyway.

**Comment by DanMiel** [comment]
Greetings  Kbwbe,
On my machine OneButton is working. In this this video I made the other day you can see the icons get activated as the features are selected. [https://youtu.be/BAwx8F5Yh7U](url)
In my testing, all of the features below the curser do show, this includes every feature of every part below the pick point.
All of the checking for constraints is done using your code. Have you been able to locate where the crash happens.
Lastly, IMHO, all code for these features is in the OneButtonDefault.py file. There has not been any change to your code. If someone tries these features and they don't like them they do not need to turn the feature on. If they don't work properly, let me chase down the problem. 
For users like me, who are accustomed to features like these, they would be a welcomed option to A2plus.
Thanks Dan


OS: Windows 10 (10.0)
Word size of FreeCAD: 64-bit
Version: 0.20.27809 (Git)
Build type: Release
Python 3.8.12, Qt 5.12.9, Coin 4.0.0, OCC 7.5.3
Locale: English/United States (en_US)
Installed mods: 
  * A2plus 0.4.56
  * Assembly4 0.11.12

**Comment by luzpaz** [comment]
Maybe the PR can be simplified broken down in to smaller changes?

**Comment by luzpaz** [comment]
Looks like this was merged in to the tmp branch. Using the addon manager feature we could have testers test the feature by pulling that branch (I've mentioned this before)

**Pull request merged**
