### PR TITLE
Add Videos into README.md

### PR DESCRIPTION
**Pull request by Symbian9**

### CODE REVIEW

**Comment by kbwbe** [comment]
Hi,
thank you for your PR. In generally, i think it is a good idea to have some videos within the README.md

The "kitchen cabinet assembly" video is ok. I do not prefer having the "using compound" video in the video section, as it does not much deal with A2plus.

On your youtube channel, i have seen your video "Assembley drawer". (Please correct the title from "Assembley" to "Assembly). This one seems to be more suitable to A2plus.

Please do a new PR with the changed video list. Then i will merge it to master.
Thank you.

**Comment by Symbian9** [comment]
FTR, This is not my channel.

**Comment by kbwbe** [comment]
The video section is now inside README.md
I replaced the videos by an own one, to avoid copyright issues.

**Comment by Symbian9** [comment]
> I replaced the videos by an own one, to avoid copyright issues.

There could not be any issues as it is just reference links.

**Pull request merged**
