### PR TITLE
Add new column to viewer.

### PR DESCRIPTION
**Pull request by DanMiel**
Better error descriptions for the CD files.

### CODE REVIEW

**Comment by luzpaz** [comment]
Link to https://github.com/kbwbe/A2plus/issues/505

**Comment by luzpaz** [comment]
@DanMiel looks like this branch is conflicting, can you rebase and fix the issues?

**Comment by DanMiel** [comment]
luzpaz: kbwbe added some translating functions in the code. I'll need to cancel the PR and go through the changed files line by line. 
Is the best way to close the PR just to hit "Close"?
Perhaps it would be better to take my additions out of kbwle's files and I can make a separate add-on with them. His programing is over my head.
Dan

**Comment by luzpaz** [comment]
I guess you can make an addon on an addon. But translations are a beast by themselves. It's not super complicated once you understand https://wiki.freecadweb.org/Translating_an_external_workbench

**Comment by DanMiel** [comment]
It doesn't look like the translations are bad (thanks for the link). My tremors have gotten worse, and it takes me a while me a long time to select things on the computer and type. The changes I did on the files were fairly major so it will take me a while to add them to kbwbe's files. Please be patient.

**Comment by DanMiel** [comment]
luzpaz: I fixed the files and instead of reopening this PR I opened PR536 to update my CD (Constraint Diagnostic) files. These files do not affect PR 505 which are kbwbe's files.
Dan

**Pull request closed without merging**
